# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/tayz_decoding',
                'doc_host': 'https://khankanz.github.io',
                'git_url': 'https://github.com/khankanz/tayz_decoding',
                'lib_path': 'tayz_decoding'},
  'syms': {'tayz_decoding.core': {'tayz_decoding.core.foo': ('parsers.html#foo', 'tayz_decoding/core.py')}}}
