# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_types.ipynb.

# %% auto 0
__all__ = ['CreateCRANEChatCompletionResponse']

# %% ../nbs/02_types.ipynb 3
from typing import TypedDict, Literal
from llama_cpp.llama_types import ChatCompletionResponseChoice, CompletionUsage
from pydantic import BaseModel

# %% ../nbs/02_types.ipynb 4
class CreateCRANEChatCompletionResponse(TypedDict):
    id: str
    object: Literal["crane.chat.completion"]
    # created: int
    # model: str
    completion: ChatCompletionResponseChoice
    json: BaseModel
    # usage: CompletionUsage
