# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/02_types.ipynb.

# %% auto 0
__all__ = ['Parser']

# %% ../nbs/02_types.ipynb 4
class Parser:
    """
    Parser class.

    Default behavior:
    - `parse` returns text as-is
    - `parse_answer` returns the last message's content (or text if string)
    """
    def __init__(self, xfn: Callable[[str], str] = lambda x: x):
        self.logger = logging.getLogger(f"tayz-decoding.parsers.{self.__class__.__name__}")
        self.xfn = xfn
    def parse(self, txt: str) -> Any: return self.xfn(txt)
